packages:
  - "packages/*"
allowBuilds:
  "@parcel/watcher": true
  "@prisma/engines": true
  "@sentry/cli": true
  better-sqlite3: true
  core-js: true
  esbuild: true
  maplibre-gl: true
  prisma: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
overrides:
  "@vue/devtools-kit": ">=8.0.3"
  "better-sqlite3": ">=12.6.2"
  "is-async-function": 2.1.0
  "sharp": "latest"
  "vite": "^8"
